### ISSUE TITLE
FW does not run on Dell KH08P PCIe card

### ISSUE THREAD

**Issue by jonsger** [meklort/bcm5719-fw#18] opened 2020-01-23 17:11 UTC
Hi,

I have a blackbird at home and want to try this firmware. As I didn't want to brick my expensive blackbird, I ordered a Dell KH08P PCIe network card with a bcm5719. I built the software on commit 550345e. I checked the card with the proprietary firmware before and it worked on my intel machine.

Here is what I did (everything as root):
```
echo 0000:01:00.0 > /sys/bus/pci/devices/0000\:01\:00.0/driver/unbind
echo 0000:01:00.1 > /sys/bus/pci/devices/0000\:01\:00.1/driver/unbind
echo 0000:01:00.2 > /sys/bus/pci/devices/0000\:01\:00.2/driver/unbind
echo 0000:01:00.3 > /sys/bus/pci/devices/0000\:01\:00.3/driver/unbind
```
Can also be achieved by `rmmod tg3`, afaik.

```
./utils/bcmflash/bcmflash -t hardware -1 stage1/stage1.bin
```

I was told to copy the firmware to `/lib/firmware/tigon` before modprobing:
```
cp stage1/stage1.bin /lib/firmware/tigon/tg3.bin
xz --compress /lib/firmware/tigon/tg3.bin
modprobe tg3
```
At least something did worked:
```
ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
[...]
2: em1: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc pfifo_fast state DOWN group defa
ult qlen 1000
[not connected ethernet chip on mainboard]
7: enp1s0f0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether 00:0a:f7:2f:4e:44 brd ff:ff:ff:ff:ff:ff
8: p1p1: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc mq state DOWN group default qlen 1000
    link/ether 00:0a:f7:2f:4e:45 brd ff:ff:ff:ff:ff:ff
9: p1p2: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether 00:0a:f7:2f:4e:46 brd ff:ff:ff:ff:ff:ff
10: p1p3: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether 00:0a:f7:2f:4e:47 brd ff:ff:ff:ff:ff:ff
```

Getting it up with `wicked ifup enp1s0f0` didn't worked. So I had a look at `dmesg`:
```
[  627.839861] tg3.c:v3.137 (May 11, 2014)
[  627.861445] tg3 0000:01:00.0 eth0: Tigon3 [partno(BCM95719) rev 5719001] (PCI Express) M
AC address 00:0a:f7:2f:4e:44
[  627.861449] tg3 0000:01:00.0 eth0: attached PHY is 5719C (10/100/1000Base-T Ethernet) (W
ireSpeed[1], EEE[1])
[  627.861452] tg3 0000:01:00.0 eth0: RXcsums[1] LinkChgREG[0] MIirq[0] ASF[1] TSOcap[1]
[  627.861454] tg3 0000:01:00.0 eth0: dma_rwctrl[00000001] dma_mask[64-bit]
[  627.888725] tg3 0000:01:00.1 eth1: Tigon3 [partno(BCM95719) rev 5719001] (PCI Express) MAC address 00:0a:f7:2f:4e:45
[  627.888728] tg3 0000:01:00.1 eth1: attached PHY is 5719C (10/100/1000Base-T Ethernet) (WireSpeed[1], EEE[1])
[  627.888730] tg3 0000:01:00.1 eth1: RXcsums[1] LinkChgREG[0] MIirq[0] ASF[1] TSOcap[1]
[  627.888732] tg3 0000:01:00.1 eth1: dma_rwctrl[00000001] dma_mask[64-bit]
[  627.909423] tg3 0000:01:00.2 eth2: Tigon3 [partno(BCM95719) rev 5719001] (PCI Express) MAC address 00:0a:f7:2f:4e:46
[  627.909428] tg3 0000:01:00.2 eth2: attached PHY is 5719C (10/100/1000Base-T Ethernet) (WireSpeed[1], EEE[1])
[  627.909431] tg3 0000:01:00.2 eth2: RXcsums[1] LinkChgREG[0] MIirq[0] ASF[1] TSOcap[1]
[  627.909434] tg3 0000:01:00.2 eth2: dma_rwctrl[00000001] dma_mask[64-bit]
[  627.932413] tg3 0000:01:00.3 eth3: Tigon3 [partno(BCM95719) rev 5719001] (PCI Express) MAC address 00:0a:f7:2f:4e:47
[  627.932418] tg3 0000:01:00.3 eth3: attached PHY is 5719C (10/100/1000Base-T Ethernet) (WireSpeed[1], EEE[1])
[  627.932421] tg3 0000:01:00.3 eth3: RXcsums[1] LinkChgREG[0] MIirq[0] ASF[1] TSOcap[1]
[  627.932423] tg3 0000:01:00.3 eth3: dma_rwctrl[00000001] dma_mask[64-bit]
[  627.937766] tg3 0000:01:00.0 enp1s0f0: renamed from eth0
[  627.992820] tg3 0000:01:00.2 p1p2: renamed from eth2
[  628.044300] tg3 0000:01:00.1 p1p1: renamed from eth1
[  628.099125] tg3 0000:01:00.3 p1p3: renamed from eth3
[  688.104728] e1000e: em1 NIC Link is Down
[  823.741816] tg3 0000:01:00.0 enp1s0f0: No firmware running
```

As it didn't worked out, I restored the originally fw and then rebooted the system. The second try was the same but loading the APE fw as stated in the README. But apparently this didn't made a difference. 

Did I made anything wrong? Are external PCIe cards without BMC not yet supported?

**Comment by meklort** [comment] 2020-01-24 00:45
I have not tested the firmware on an external card. I also do not know what will happen if you try replacing tg3.bin. I've never tested this and have always flashed the stage1 firmware directly to the device.

**Comment by hughsie** [comment] 2020-09-23 09:40
I too have the KH08P and need to know how to construct the flash image. The nonfree KH08P image is much like the Blackbird (info, vpd, info2, stage1, stage2) but it has a lot more code dictionaries. The blackbird firmware only has the APE (dell calls this the NCSI), but the KH08P also has the large OptionROM as a PE binary (Dell calls this the MBA, HP calls this the PXE) as well as two copies of seemingly identical ISCSI blob as well as what looks like a config section and another vendor specific section.

To construct a NVRAM image, should I leave the other code modules in place (I'm assuming ones like the ISCSI ones will just be ignored) or strip them out? I do see the benefit to having a 0% nonfree firmware image in the SPI from a marketing point of view. The stage2 image can be a zero sized section if I understand correctly. The option rom is also sitting in code dictionary _index zero_, so to speak, with APE currently in slot 1, and I don't know if the free software stage1 is looking for the APE by address (0x7 iirc) or just assuming it's the first index in the code dictionary.

**Comment by meklort** [comment] 2020-09-24 00:15
@hughsie IF you use the free stage1.bin file, then it will not handle any of the code directory images. My understanding is that the nonfree code *does* handle the options rom, however. 

The APE itself has a bootloader that locates the appropriate APE image. I'll do some testing to see if this has to be in slot 1 or if it can be elsewhere.

What should work is constructing a free-only binary that contains stage1.bin, ape1.bin in slot 1, and the header / manufacturer section from the original NVRAM. I'll look into constructing a fully valid firmware image here, as well as doing some tests on loading the APE as I also have a copy of this card.

**Comment by meklort** [comment] 2020-09-24 05:00
I've done some testing here, and it looks like the APE bootloader in ROM is able to handle loading the APE firmware from any code directory.

**Comment by meklort** [comment] 2020-09-24 05:13
Also note that I can confirm that the APE firmware is able to start up on the KH08P when in directory 1. This was tested without erasing the other directories (and updating the stage1 code).

I also did *not* modify the address (0x00010000), and everything still booted up.

Note that on the KH08P, the APE firmware doesn't do too much right now, as it only handles NCSI, which can't really be used on the add-in card. Custom APE payloads could be loaded to do other things, however. To be clear - you can run the card without the APE firmware and it will still function.

For reference (0001:01:00.2 is the add-in card)
meklort@talos2 ~/g/b/build (master) [255]> 
sudo ./utils/apeconsole/apeconsole -f2
Found supported device 14e4:1657 at /sys/bus/pci/devices//0001:01:00.2/config
mmaping BAR[0]: /sys/bus/pci/devices//0001:01:00.2/resource0
mmaping BAR[2]: /sys/bus/pci/devices//0001:01:00.2/resource2
mmaping BAR[4]: /sys/bus/pci/devices//0001:01:00.2/resource4
APE v0.4.385 NCSI Port 0
VMAINPowerStatus: 1

**Comment by hughsie** [comment] 2020-09-24 15:21
Does the KH08P have a different subsystem PID to the talos systems? Do you plan of changing the subsystem ID for the free firmware, and in which case does that mean that we need different stage1.bin images for KH08P and the Blackbird?

**Comment by meklort** [comment] 2020-09-24 18:15
Yes the Dell card has a different subsystem Id. 
Stage1.bin file won't need to change between the two, just the headed/manufacturing info section.

**Comment by hughsie** [comment] 2020-09-25 08:23
> Stage1.bin file won't need to change between the two, just the header/manufacturing info section

I thought you said you were thinking of changing the subsys ID for the open source firmware? How would you do that if you also respect the subsystem IDs in the `info` block?

**Comment by meklort** [comment] 2020-09-25 23:32
So, this is what I see on the Talos II and the Dell KH08P:
Dell: 14e4:1657, Subsystem 14e4:1904
Talos II: 14e4:1657, subsystem 14e4:1981

Personally, the only reason I see to change the PID/VIDs is so that fwupd can detect the free firmware and enable updates properly If this can be done using the firmware version string instead, that might be better.

That said, I can modify the free stage1 binary in *all* cases to set the subsystem VID to be something new, such as SubVID = VID | 0x8000, which would result in the following:
Dell: 14e4:1657, Subsystem 94e4:1904
Talos II: 14e4:1657, subsystem 94e4:1981

Then fwupd could use the 94e4 subsytem id to mean "user has opted in to updates oss updates" (of course, with the firmware branch feature you're working on, the user could opt in, which would the change the subsystem id).

Let me know what works best for fwupd.

**Comment by hughsie** [comment] 2020-09-26 11:18
> If this can be done using the firmware version string instead

I think from a fwupd point of view we just need a simple way of recording what branch we're on in the currently running hardware. I guess in theory there could be the reference broadcom firmware, the dell firmware, your firmware and my local test firmware. If we could read out a short _string_ from the firmware (e.g. where the broadcom firmware is always `\0` or `\xff`, and yours reads out `oss` or something) then that means we don't need to hardcode anything in fwupd.

**Comment by meklort** [comment] 2020-10-30 02:00
I'm going to go ahead and close this issue.
- The latest repository provides a fwupd .cab file that can be used to flash firmware to the dell card.
- The APE firmware can run on the card and provides console printout.

That sadi, the firmware does *not* support NCSI over SMBus, and so this firmware does not have feature parity with the card when used in a Dell server.
It can, however be used for some interesting experiments if anyone wants to (such as putting a tcp/ip stack on the arm processor and running a random web server off of it, or something).
Additionally, firmware card does *not* include support  for exposing an option rom to the host at the moment, and so it will not be bootable on an x86 machine. Additionally, iPXE doesn't really have a signed UEFI blob that can easily be injected here either, so it's be a bit more complicated to get things runing.

Note: I may look at both issues I mentioned above (NCSI over SMBus, and exporting an option rom), but it's not a priority right now.

**Closed by meklort** 2020-10-30 02:00 UTC
